# Generated by Django 6.0.6 on 2026-06-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='property_gallery/'),
        ),
    ]
