# Generated by Django 6.0.6 on 2026-06-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='total_amount',
            new_name='price',
        ),
    ]
