# Generated by Django 6.0.6 on 2026-06-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_payment_is_refunded_payment_refunded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
