# Generated by Django 6.0.6 on 2026-06-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_payment_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
